---
name: test
on:
  pull_request:
  push:

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker tag action
        id: tag
        uses: ./

      - name: Test
        run: |
          echo "${{ steps.tag.outputs.docker-tag }}"
